-- WARNING: This will delete all existing data!
-- Run this if you want to start fresh and ensure the schema matches the code perfectly.

DROP TABLE IF EXISTS public.items;

create table public.items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  url text,
  summary text,
  author text default 'anonymous',
  category text,
  created_by uuid references auth.users(id),
  points int default 0,
  parent_id bigint references public.items(id)
);

-- Turn on Row Level Security
alter table public.items enable row level security;

-- Allow public read access
create policy "Public items are viewable by everyone"
  on public.items for select
  using ( true );

-- Allow authenticated insert access
create policy "Authenticated users can insert items"
  on public.items for insert
  to authenticated
  with check ( true );

-- Insert some dummy data
insert into public.items (title, url, author, points, category, summary) values
('Welcome to News App', 'https://example.com', 'admin', 100, 'News', 'Welcome to the news app!'),
('Supabase is awesome', 'https://supabase.com', 'dev', 50, 'Tech', 'Supabase is an open source Firebase alternative.');
