-- Create table if it doesn't exist
create table if not exists public.items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  url text,
  summary text,
  author text default 'anonymous',
  category text,
  created_by uuid references auth.users(id),
  points int default 0,
  parent_id bigint references public.items(id)
);

-- Safely add columns if they are missing (Postgres 9.6+)
alter table public.items add column if not exists summary text;
alter table public.items add column if not exists created_by uuid references auth.users(id);
alter table public.items add column if not exists category text;


-- Turn on Row Level Security
alter table public.items enable row level security;

-- Create policies (drop first to avoid conflicts if re-running)
drop policy if exists "Public items are viewable by everyone" on public.items;
create policy "Public items are viewable by everyone" on public.items for select using (true);

drop policy if exists "Authenticated users can insert items" on public.items;
create policy "Authenticated users can insert items" on public.items for insert to authenticated with check (true);

-- ─── Comments ───
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  item_id bigint not null references public.items(id) on delete cascade,
  user_id uuid not null references auth.users(id),
  author_name text not null,
  content text not null
);

alter table public.comments enable row level security;

drop policy if exists "Comments are viewable by everyone" on public.comments;
create policy "Comments are viewable by everyone" on public.comments for select using (true);

drop policy if exists "Authenticated users can insert comments" on public.comments;
create policy "Authenticated users can insert comments" on public.comments for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can delete own comments" on public.comments;
create policy "Users can delete own comments" on public.comments for delete to authenticated using (auth.uid() = user_id);

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
