-- Create table if it doesn't exist
create table if not exists public.items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  url text,
  summary text,
  author text default 'anonymous',
  category text,
  created_by uuid references auth.users(id),
  points int default 0,
  parent_id bigint references public.items(id)
);

-- Safely add columns if they are missing (Postgres 9.6+)
alter table public.items add column if not exists summary text;
alter table public.items add column if not exists created_by uuid references auth.users(id);
alter table public.items add column if not exists category text;


-- Turn on Row Level Security
alter table public.items enable row level security;

-- Create policies (drop first to avoid conflicts if re-running)
drop policy if exists "Public items are viewable by everyone" on public.items;
create policy "Public items are viewable by everyone" on public.items for select using (true);

drop policy if exists "Authenticated users can insert items" on public.items;
create policy "Authenticated users can insert items" on public.items for insert to authenticated with check (true);

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
