-- v0.4 Part B — 온톨로지 (노드·엣지)
-- Supabase Dashboard → SQL Editor에서 실행

-- ─── 통합 노드 ───
create table if not exists public.ontology_nodes (
  id bigint generated by default as identity primary key,
  node_type text not null check (node_type in ('item','tag','category','concept','person')),
  ref_id bigint,
  slug text unique,
  name text not null,
  description text,
  created_at timestamptz default now()
);

create index if not exists idx_ontology_nodes_type_ref on public.ontology_nodes (node_type, ref_id);

alter table public.ontology_nodes enable row level security;

drop policy if exists "Ontology nodes viewable by everyone" on public.ontology_nodes;
create policy "Ontology nodes viewable by everyone"
  on public.ontology_nodes for select using (true);

drop policy if exists "Admins can manage ontology nodes" on public.ontology_nodes;
create policy "Admins can manage ontology nodes"
  on public.ontology_nodes for all to authenticated
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin = true));

-- ─── 엣지 ───
create table if not exists public.ontology_edges (
  id bigint generated by default as identity primary key,
  from_node bigint references public.ontology_nodes(id) on delete cascade not null,
  to_node bigint references public.ontology_nodes(id) on delete cascade not null,
  relation text not null check (relation in (
    'tagged_with','belongs_to','is_subtype_of','related_to',
    'precedes','mentions','authored_by','covers'
  )),
  weight numeric default 1.0,
  created_at timestamptz default now(),
  unique (from_node, to_node, relation)
);

create index if not exists idx_ontology_edges_from on public.ontology_edges (from_node, relation);
create index if not exists idx_ontology_edges_to on public.ontology_edges (to_node, relation);

alter table public.ontology_edges enable row level security;

drop policy if exists "Ontology edges viewable by everyone" on public.ontology_edges;
create policy "Ontology edges viewable by everyone"
  on public.ontology_edges for select using (true);

drop policy if exists "Admins can manage ontology edges" on public.ontology_edges;
create policy "Admins can manage ontology edges"
  on public.ontology_edges for all to authenticated
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin = true));

-- ─── 기존 카테고리 → 노드 동기화 ───
insert into public.ontology_nodes (node_type, ref_id, slug, name)
select 'category', id, 'cat-' || slug, name
from public.categories
on conflict (slug) do nothing;

-- ─── concept 시드 (PNA 워크샵 프레임워크 + AI 핵심 개념) ───
insert into public.ontology_nodes (node_type, slug, name, description) values
  ('concept', 'scqa', 'S-C-Q-A', 'Situation-Complication-Question-Answer 프레임워크'),
  ('concept', 'mece', 'MECE / Logic Tree', '상호배제·전체포괄 구조 분해'),
  ('concept', 'tdcc', 'TDCC', '후행지표-선행지표 인과 분해'),
  ('concept', '5whys', '5-Whys', '근본 원인 추적 기법'),
  ('concept', 'xyz-hypothesis', 'XYZ 가설', 'If-Then-Because 가설 검증'),
  ('concept', 'design-thinking', 'Design Thinking', '공감-정의-아이디어-프로토타입-테스트'),
  ('concept', 'lean-startup', 'Lean Startup', 'Build-Measure-Learn 순환'),
  ('concept', 'carrying-capacity', 'Carrying Capacity', 'MAU = Inflow / Churn 구조'),
  ('concept', 'llm', 'LLM', '대규모 언어 모델'),
  ('concept', 'ai-agents', 'AI Agents', 'LLM 기반 자율 에이전트'),
  ('concept', 'rag', 'RAG', '검색 증강 생성'),
  ('concept', 'prompt-engineering', 'Prompt Engineering', '프롬프트 설계 기법'),
  ('concept', 'vibe-coding', 'Vibe Coding', 'AI 기반 코딩'),
  ('concept', 'pmf', 'PMF', 'Product-Market Fit'),
  ('concept', 'growth-hacking', 'Growth Hacking', '데이터 기반 성장 전략'),
  ('concept', 'jtbd', 'JTBD', 'Jobs to Be Done')
on conflict (slug) do nothing;

-- ─── person 시드 (PNA 관련 인물) ───
insert into public.ontology_nodes (node_type, slug, name, description) values
  ('person', 'jeong-seungwon', '정승원', 'PNA 운영진'),
  ('person', 'jeong-gyeongjin', '정경진', '데이터방앗간 CEO'),
  ('person', 'jeong-jaeyong', '정재용', '더크림유니언 AX Lab 디렉터'),
  ('person', 'kwon-sunseon', '권순선', 'Google AI Developer Program 리드')
on conflict (slug) do nothing;

-- ─── concept 간 관계 시드 ───
-- 프레임워크 관계
insert into public.ontology_edges (from_node, to_node, relation)
select a.id, b.id, 'related_to'
from public.ontology_nodes a, public.ontology_nodes b
where a.slug = 'scqa' and b.slug = 'mece'
on conflict do nothing;

insert into public.ontology_edges (from_node, to_node, relation)
select a.id, b.id, 'related_to'
from public.ontology_nodes a, public.ontology_nodes b
where a.slug = 'tdcc' and b.slug = '5whys'
on conflict do nothing;

insert into public.ontology_edges (from_node, to_node, relation)
select a.id, b.id, 'related_to'
from public.ontology_nodes a, public.ontology_nodes b
where a.slug = 'lean-startup' and b.slug = 'xyz-hypothesis'
on conflict do nothing;

insert into public.ontology_edges (from_node, to_node, relation)
select a.id, b.id, 'related_to'
from public.ontology_nodes a, public.ontology_nodes b
where a.slug = 'llm' and b.slug = 'ai-agents'
on conflict do nothing;

insert into public.ontology_edges (from_node, to_node, relation)
select a.id, b.id, 'related_to'
from public.ontology_nodes a, public.ontology_nodes b
where a.slug = 'llm' and b.slug = 'rag'
on conflict do nothing;

insert into public.ontology_edges (from_node, to_node, relation)
select a.id, b.id, 'related_to'
from public.ontology_nodes a, public.ontology_nodes b
where a.slug = 'ai-agents' and b.slug = 'prompt-engineering'
on conflict do nothing;

insert into public.ontology_edges (from_node, to_node, relation)
select a.id, b.id, 'is_subtype_of'
from public.ontology_nodes a, public.ontology_nodes b
where a.slug = 'rag' and b.slug = 'llm'
on conflict do nothing;

insert into public.ontology_edges (from_node, to_node, relation)
select a.id, b.id, 'related_to'
from public.ontology_nodes a, public.ontology_nodes b
where a.slug = 'pmf' and b.slug = 'growth-hacking'
on conflict do nothing;

insert into public.ontology_edges (from_node, to_node, relation)
select a.id, b.id, 'related_to'
from public.ontology_nodes a, public.ontology_nodes b
where a.slug = 'design-thinking' and b.slug = 'jtbd'
on conflict do nothing;

-- 스키마 캐시 갱신
notify pgrst, 'reload schema';
