-- v0.4 — 카테고리·태그 체계
-- Supabase Dashboard → SQL Editor에서 실행

-- ─── 카테고리 (위계형 2단계) ───
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  parent_id bigint references public.categories(id),
  sort_order int default 0,
  created_at timestamptz default now()
);

alter table public.categories enable row level security;

drop policy if exists "Categories viewable by everyone" on public.categories;
create policy "Categories viewable by everyone"
  on public.categories for select using (true);

-- ─── 태그 (평면형) ───
create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  usage_count int default 0,
  created_at timestamptz default now()
);

alter table public.tags enable row level security;

drop policy if exists "Tags viewable by everyone" on public.tags;
create policy "Tags viewable by everyone"
  on public.tags for select using (true);

drop policy if exists "Authenticated users can create tags" on public.tags;
create policy "Authenticated users can create tags"
  on public.tags for insert to authenticated with check (true);

-- ─── 아이템 ↔ 태그 (다대다) ───
create table if not exists public.item_tags (
  item_id bigint references public.items(id) on delete cascade,
  tag_id bigint references public.tags(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (item_id, tag_id)
);

alter table public.item_tags enable row level security;

drop policy if exists "Item tags viewable by everyone" on public.item_tags;
create policy "Item tags viewable by everyone"
  on public.item_tags for select using (true);

drop policy if exists "Authenticated users can manage item tags" on public.item_tags;
create policy "Authenticated users can manage item tags"
  on public.item_tags for insert to authenticated with check (true);

-- ─── items에 category_id 추가 ───
alter table public.items
  add column if not exists category_id bigint references public.categories(id);

-- ─── 카테고리 시드 데이터 ───
-- 대분류
insert into public.categories (slug, name, sort_order) values
  ('ai', 'AI', 1),
  ('product', 'Product', 2),
  ('engineering', 'Engineering', 3),
  ('business', 'Business', 4),
  ('community', 'Community', 5)
on conflict (slug) do nothing;

-- 소분류
insert into public.categories (slug, name, parent_id, sort_order) values
  ('ai-llm', 'LLM', (select id from public.categories where slug = 'ai'), 1),
  ('ai-agents', 'Agents', (select id from public.categories where slug = 'ai'), 2),
  ('ai-rag', 'RAG', (select id from public.categories where slug = 'ai'), 3),
  ('ai-paper', '논문', (select id from public.categories where slug = 'ai'), 4),
  ('ai-tool', 'Tool', (select id from public.categories where slug = 'ai'), 5),
  ('product-growth', 'Growth', (select id from public.categories where slug = 'product'), 1),
  ('product-pmf', 'PMF', (select id from public.categories where slug = 'product'), 2),
  ('product-pricing', 'Pricing', (select id from public.categories where slug = 'product'), 3),
  ('product-ux', 'UX Research', (select id from public.categories where slug = 'product'), 4),
  ('eng-frontend', 'Frontend', (select id from public.categories where slug = 'engineering'), 1),
  ('eng-backend', 'Backend', (select id from public.categories where slug = 'engineering'), 2),
  ('eng-data', 'Data', (select id from public.categories where slug = 'engineering'), 3),
  ('eng-devops', 'DevOps', (select id from public.categories where slug = 'engineering'), 4),
  ('biz-startup', '스타트업', (select id from public.categories where slug = 'business'), 1),
  ('biz-investment', '투자', (select id from public.categories where slug = 'business'), 2),
  ('biz-sv', '실리콘밸리', (select id from public.categories where slug = 'business'), 3),
  ('community-pna', 'PNA 내부', (select id from public.categories where slug = 'community'), 1),
  ('community-event', '이벤트', (select id from public.categories where slug = 'community'), 2),
  ('community-interview', '인터뷰', (select id from public.categories where slug = 'community'), 3)
on conflict (slug) do nothing;

-- ─── 기존 items.category 텍스트 → category_id 매핑 ───
-- 기존 값(Article, Trend, News, Resource, Seminar)을 대분류에 매핑
update public.items set category_id = (select id from public.categories where slug = 'ai')
  where category in ('Trend') and category_id is null;
update public.items set category_id = (select id from public.categories where slug = 'business')
  where category in ('News') and category_id is null;
update public.items set category_id = (select id from public.categories where slug = 'engineering')
  where category in ('Resource') and category_id is null;
update public.items set category_id = (select id from public.categories where slug = 'community')
  where category in ('Seminar') and category_id is null;
-- 나머지(Article 등)는 AI 기본값
update public.items set category_id = (select id from public.categories where slug = 'ai')
  where category_id is null;

-- 스키마 캐시 갱신
notify pgrst, 'reload schema';
